### ISSUE TITLE
#ToDO: MIPMAP Java Security patches and upgrade of depreciated Log4j 1.X

### ISSUE THREAD

**Issue by lanawwas** [aueb-wim/DataQualityControlTool#6]
The JAVA library Log4j 1.X used in MIPMAP Java engine is depreciated or with known security vulnerabilities and it should be revised with proper upgrades or Security patches! 

"On August 5, 2015 the Logging Services Project Management Committee announced that Log4j 1.x had reached end of life. For complete text of the announcement please see the Apache Blog. "

Reference: https://logging.apache.org/log4j/1.2/

Users of Log4j 1 are recommended to upgrade to Apache Log4j 2

**Comment by iosifsp** [comment]
I've push a new image of mipmap in dockerhub which uses the updated log4j version.
